import {ThemePropertiesType} from '../types';

export const darkTheme: ThemePropertiesType = {
  colors: {
    primary: '',
    onPrimary: '',
    primaryContainer: '',
    onPrimaryContainer: '',
    secondary: '',
    onSecondary: '',
    secondaryContainer: '',
    onSecondaryContainer: '',
    tertiary: '',
    onTertiary: '',
    tertiaryContainer: '',
    onTertiaryContainer: '',
    error: '',
    onError: '',
    errorContainer: '',
    onErrorContainer: '',
    success: '',
    onSuccess: '',
    successContainer: '',
    onSuccessContainer: '',
    background: '',
    onBackground: '',
    surface: '',
    onSurface: '',
    surfaceVariant: '',
    onSurfaceVariant: '',
    outline: '',
    outlineVariant: '',
  },
  elevation: {
    surface: '',
    surface1: '',
    surface2: '',
    surface3: '',
    surface4: '',
    surface5: '',
  },
  typography: {
    displaySmall: {
      fontFamily: '',
      fontWeight: '400',
      lineHeight: 0,
      fontSize: 0,
    },
    displayMedium: {
      fontFamily: '',
      fontWeight: '400',
      lineHeight: 0,
      fontSize: 0,
    },
    displayLarge: {
      fontFamily: '',
      fontWeight: '400',
      lineHeight: 0,
      fontSize: 0,
    },
    headlineSmall: {
      fontFamily: '',
      fontWeight: '400',
      lineHeight: 0,
      fontSize: 0,
    },
    headlineMedium: {
      fontFamily: '',
      fontWeight: '400',
      lineHeight: 0,
      fontSize: 0,
    },
    headlineLarge: {
      fontFamily: '',
      fontWeight: '400',
      lineHeight: 0,
      fontSize: 0,
    },
    titleSmall: {
      fontFamily: '',
      fontWeight: '400',
      lineHeight: 0,
      fontSize: 0,
    },
    titleMedium: {
      fontFamily: '',
      fontWeight: '400',
      lineHeight: 0,
      fontSize: 0,
    },
    titleLarge: {
      fontFamily: '',
      fontWeight: '400',
      lineHeight: 0,
      fontSize: 0,
    },
    bodySmall: {
      fontFamily: '',
      fontWeight: '400',
      lineHeight: 0,
      fontSize: 0,
    },
    bodyMedium: {
      fontFamily: '',
      fontWeight: '400',
      lineHeight: 0,
      fontSize: 0,
    },
    bodyLarge: {
      fontFamily: '',
      fontWeight: '400',
      lineHeight: 0,
      fontSize: 0,
    },
    labelSmall: {
      fontFamily: '',
      fontWeight: '400',
      lineHeight: 0,
      fontSize: 0,
    },
    labelMedium: {
      fontFamily: '',
      fontWeight: '400',
      lineHeight: 0,
      fontSize: 0,
    },
    labelLarge: {
      fontFamily: '',
      fontWeight: '400',
      lineHeight: 0,
      fontSize: 0,
    },
  },
};
